### ISSUE TITLE
Can't run it

### ISSUE THREAD

**Issue by sirishere** [BOTFritz/BOTFritz#4]
Hello, after installing all dependencies and running main.py in my command prompt (on windows 10 ltsc build 1809), I get this error : 

```
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import screenshot
  File "C:\Users\Beri\Desktop\BOTFritz-master\screenshot.py", line 3, in <module>
    import mss
  File "C:\Users\Beri\AppData\Local\Programs\Python\Python35\lib\site-packages\mss\__init__.py", line 12, in <module>
    from .exception import ScreenShotError
  File "C:\Users\Beri\AppData\Local\Programs\Python\Python35\lib\site-packages\mss\exception.py", line 6, in <module>
    from typing import TYPE_CHECKING
ImportError: cannot import name 'TYPE_CHECKING'
```

Using python 3.5

**Comment by xRowest** [comment]
Bro I don't know how to do it. Can you add it from discord please. AlpDeus#9974
